name: Studio - Mac M1 手动

on:
  workflow_dispatch: {}

jobs:

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-arm64]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Clean cache
        run: arch -arm64 yarn cache clean

      - name: Check dependencies
        run: "arch -arm64 yarn install --frozen-lockfile --network-timeout 100000"

      - name: Remove dist directory
        if: "!startsWith(matrix.os, 'windows')"
        run: rm -rf ./apps/studio/dist_electron
      - name: Remove dist directory windows
        if: startsWith(matrix.os, 'windows')
        run: Remove-Item dist_electron -Recurse -ErrorAction Ignore
      - name: Build and Publish
        run: cd apps/studio && arch -arm64 yarn run electron:build --arm64 --x64 --publish never
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: apps/studio/dist_electron
      - name: Cleanup artifacts
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          npx rimraf "apps/studio/dist_electron/!(*.exe|*.deb|*.rpm|*.AppImage|*.dmg|*.snap)"
